version: "3.7"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    networks:
      gitlab_network:
        ipv4_address: 172.16.0.2
    ports:
      - 80:80
      - 8061:8061
    volumes:
      - $PWD/gitlab/config:/etc/gitlab
      - $PWD/gitlab/logs:/var/log/gitlab
      - $PWD/gitlab/data:/var/opt/gitlab
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.dev.com/'
        mattermost_external_url 'http://gitlab.dev.com:8061/'
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    networks:
      gitlab_network:
        ipv4_address: 172.16.0.3
    volumes:
      - $PWD/gitlab-runner/config:/etc/gitlab-runner
    depends_on:
      - gitlab
  redmine-mysql:
    restart: always
    image: mysql:5.7.32
    container_name: redmine-mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
      MYSQL_DATABASE: redmine
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - $PWD/redmine/mysql:/var/lib/mysql
    networks:
      gitlab_network:
        ipv4_address: 172.16.0.4
  redmine:
    restart: always
    image: redmine:latest
    container_name: redmine
    depends_on:
      - redmine-mysql
    networks:
      gitlab_network:
        ipv4_address: 172.16.0.5
    ports:
      - 10083:3000
    environment:
      TZ: Asia/Tokyo
      REDMINE_DB_MYSQL: redmine-mysql
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_ENCODING: utf8mb4
    volumes:
      - $PWD/redmine/redmine:/home/redmine/data
  dns:
    image: andyshinn/dnsmasq
    container_name: dns
    ports:
      - 53:53/udp
      - 53:53/tcp
    volumes:
      - $PWD/dns/dnsmasq.conf:/etc/dnsmasq.conf
      - $PWD/dns/hosts:/etc/hosts
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      gitlab_network:
        ipv4_address: 172.16.0.6
networks:
  gitlab_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
